// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trvjuxwulzursylufoqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRydmp1eHd1bHp1cnN5bHVmb3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTY2MjAsImV4cCI6MjA3MzU5MjYyMH0.zWR1WJRNhSqNBmQwtF7JaHmHjBSYGxYmH-pqFZNg0fY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});